name: magickit

packages:
  - packages/**
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- flutter analyze
    description: Analyze code in all packages

  test:
    run: melos exec -- flutter test
    description: Run tests in all packages

  format:
    run: melos exec -- dart format .
    description: Format code in all packages

  clean:
    run: melos exec -- flutter clean
    description: Clean build artifacts in all packages
