name: magickit

packages:
  - packages/**
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  publish:dry:
    run: melos publish --dry-run
    description: Dry run publish for all publishable packages

  publish:
    run: melos publish --no-dry-run
    description: Publish all publishable packages to pub.dev
  analyze:
    run: melos exec -- flutter analyze
    description: Analyze code in all packages

  test:
    run: melos exec -- flutter test
    description: Run tests in all packages

  format:
    run: melos exec -- dart format .
    description: Format code in all packages

  clean:
    run: melos exec -- flutter clean
    description: Clean build artifacts in all packages
