import '../utils/string_utils.dart';

class AssetGenerator {
  /// Generate MagicAssets class dari list file paths.
  ///
  /// [inputDir]     — root folder assets (e.g., 'assets/')
  /// [allFiles]     — semua file paths (relative atau absolute)
  /// [exclude]      — subfolder yang di-skip (e.g., ['l10n'])
  /// [groups]       — mapping groupName → subfolder (e.g., {'icons': 'icons'})
  /// [stripPrefix]  — prefix filename yang dihapus (e.g., ['ic_', 'img_'])
  String generate({
    required String inputDir,
    required List<String> allFiles,
    required List<String> exclude,
    required Map<String, String> groups,
    required List<String> stripPrefix,
  }) {
    final basePrefix =
        inputDir.replaceAll(r'\', '/').endsWith('/')
            ? inputDir.replaceAll(r'\', '/')
            : '${inputDir.replaceAll(r'\', '/')}/';

    final entries = <_AssetEntry>[];
    for (final file in allFiles) {
      final normalized = file.replaceAll(r'\', '/');

      String relative;
      if (normalized.startsWith(basePrefix)) {
        relative = normalized.substring(basePrefix.length);
      } else {
        relative = normalized;
      }

      if (relative.isEmpty) continue;
      if (relative.split('/').any((s) => s.startsWith('.'))) continue;

      final firstSegment = relative.split('/').first;
      if (exclude.contains(firstSegment)) continue;

      entries.add(
        _AssetEntry(
          relative: relative,
          assetPath: '$basePrefix$relative',
          folder: firstSegment,
        ),
      );
    }

    entries.sort((a, b) => a.relative.compareTo(b.relative));

    final buffer = StringBuffer()
      ..writeln('// GENERATED BY MAGICKIT CLI — DO NOT MODIFY')
      ..writeln('// Run `magickit assets` to regenerate.')
      ..writeln('// ignore_for_file: lines_longer_than_80_chars')
      ..writeln();

    if (groups.isNotEmpty) {
      _generateGrouped(buffer, entries, groups, stripPrefix);
    } else {
      _generateFlat(buffer, entries, stripPrefix);
    }

    return buffer.toString();
  }

  void _generateGrouped(
    StringBuffer buffer,
    List<_AssetEntry> entries,
    Map<String, String> groups,
    List<String> stripPrefix,
  ) {
    buffer
      ..writeln('class MagicAssets {')
      ..writeln('  MagicAssets._();')
      ..writeln();

    for (final groupName in groups.keys) {
      final className = '_${capitalize(groupName)}';
      buffer.writeln('  static const $groupName = $className();');
    }
    buffer.writeln('}');

    for (final groupEntry in groups.entries) {
      final groupName = groupEntry.key;
      final folder = groupEntry.value.replaceAll('/', '');
      final className = '_${capitalize(groupName)}';

      final groupFiles = entries.where((e) => e.folder == folder).toList();

      buffer
        ..writeln()
        ..writeln('class $className {')
        ..writeln('  const $className();')
        ..writeln();

      // Track previous subfolder for comment separators
      String? lastSubfolder;
      for (final file in groupFiles) {
        final parts = file.relative.split('/');
        final withinGroup = parts.skip(1).toList(); // strip group folder prefix

        // Comment separator when subfolder changes
        if (withinGroup.length > 1) {
          final sub = withinGroup.first;
          if (sub != lastSubfolder) {
            if (lastSubfolder != null) buffer.writeln();
            buffer.writeln('  // ${file.folder}/$sub/');
            lastSubfolder = sub;
          }
        } else if (lastSubfolder != null) {
          buffer.writeln();
          lastSubfolder = null;
        }

        final varName = _dedupe(_toVarName(withinGroup, stripPrefix));
        buffer.writeln("  String get $varName => '${file.assetPath}';");
      }

      buffer.writeln('}');
    }
  }

  void _generateFlat(
    StringBuffer buffer,
    List<_AssetEntry> entries,
    List<String> stripPrefix,
  ) {
    buffer
      ..writeln('class MagicAssets {')
      ..writeln('  MagicAssets._();')
      ..writeln();

    String? lastFolder;
    for (final entry in entries) {
      if (entry.folder != lastFolder) {
        if (lastFolder != null) buffer.writeln();
        buffer.writeln('  // ${entry.folder}/');
        lastFolder = entry.folder;
      }
      final varName = _toVarName(entry.relative.split('/'), stripPrefix);
      buffer.writeln(
        "  static const String $varName = '${entry.assetPath}';",
      );
    }

    buffer.writeln('}');
  }

  String _toVarName(List<String> parts, List<String> stripPrefixes) {
    final segments = <String>[];

    for (int i = 0; i < parts.length; i++) {
      var part = parts[i];
      final isLast = i == parts.length - 1;

      if (isLast) {
        // Remove extension
        if (part.contains('.')) {
          part = part.substring(0, part.lastIndexOf('.'));
        }
        // Strip known prefixes (e.g. ic_, img_)
        for (final prefix in stripPrefixes) {
          if (part.startsWith(prefix) && part.length > prefix.length) {
            part = part.substring(prefix.length);
            break;
          }
        }
      }

      final subParts =
          part.split(RegExp(r'[_\-\s]+')).where((s) => s.isNotEmpty);
      segments.addAll(subParts);
    }

    if (segments.isEmpty) return 'unknown';
    return segments.first.toLowerCase() +
        segments.skip(1).map(capitalize).join('');
  }

  // Simple dedup fallback — not stateful across calls, used only for
  // readable output. The command layer handles full dedup if needed.
  String _dedupe(String name) => name.isEmpty ? 'unknown' : name;
}

class _AssetEntry {
  final String relative;
  final String assetPath;
  final String folder;

  const _AssetEntry({
    required this.relative,
    required this.assetPath,
    required this.folder,
  });
}
