import '../utils/string_utils.dart';

class L10nGenerator {
  static const _header =
      '// GENERATED BY MAGICKIT CLI — DO NOT MODIFY\n'
      '// Run `magickit l10n` to regenerate.\n';

  /// Generate `l10n_keys.dart` — flat constant keys.
  ///
  /// [groups] — null key = general (top-level), named keys = nested groups.
  String generateKeys(Map<String?, Map<String, String>> groups) {
    final buf = StringBuffer()
      ..write(_header)
      ..writeln()
      ..writeln('class L10nKeys {')
      ..writeln('  L10nKeys._();')
      ..writeln();

    final general = groups[null];
    if (general != null) {
      for (final entry in general.entries) {
        buf.writeln("  static const String ${_keyToVar(entry.key)} = '${entry.key}';");
      }
    }

    for (final groupEntry in groups.entries) {
      if (groupEntry.key == null) continue;
      buf.writeln();
      buf.writeln('  // ${groupEntry.key}');
      for (final entry in groupEntry.value.entries) {
        buf.writeln("  static const String ${_keyToVar(entry.key)} = '${entry.key}';");
      }
    }

    buf.writeln('}');
    return buf.toString();
  }

  /// Generate `l10n_{locale}.dart` — flat translation map.
  String generateLocaleMap(String locale, Map<String, String> flatMap) {
    final localePascal = toPascalCase(locale);
    final buf = StringBuffer()
      ..write(_header)
      ..writeln('// ignore_for_file: lines_longer_than_80_chars')
      ..writeln('// Locale: $locale')
      ..writeln()
      ..writeln("const Map<String, String> l10n$localePascal = {");

    for (final entry in flatMap.entries) {
      final escaped = entry.value.replaceAll("'", r"\'");
      buf.writeln("  '${entry.key}': '$escaped',");
    }

    buf.writeln('};');
    return buf.toString();
  }

  /// Generate `getters/{group}_getters.dart` — extension with getters/methods.
  ///
  /// [entries] — key → default locale value (used for `{param}` detection).
  String generateGetters(String group, Map<String, String> entries) {
    final groupPascal = toPascalCase(group);
    final buf = StringBuffer()
      ..write(_header)
      ..writeln()
      ..writeln("import '../app_localizations.dart';")
      ..writeln()
      ..writeln('extension ${groupPascal}Getters on AppLocalizations {');

    for (final entry in entries.entries) {
      final varName = _keyToVar(entry.key);
      final params = _extractParams(entry.value);

      if (params.isEmpty) {
        buf.writeln("  String get $varName => translate('${entry.key}');");
      } else {
        final namedParams = params
            .map((p) => 'required ${_paramType(p)} $p')
            .join(', ');
        var body = "translate('${entry.key}')";
        for (final p in params) {
          final asString = _paramType(p) == 'int' ? '$p.toString()' : p;
          body += ".replaceAll('{$p}', $asString)";
        }
        buf.writeln('  String $varName({$namedParams}) => $body;');
      }
    }

    buf.writeln('}');
    return buf.toString();
  }

  /// Generate `app_localizations.dart` — main class + delegate + extension.
  String generateAppLocalizations({
    required String defaultLocale,
    required List<String> supportedLocales,
    required List<String> getterGroups,
  }) {
    final buf = StringBuffer()
      ..write(_header)
      ..writeln()
      ..writeln("import 'package:flutter/widgets.dart';");

    for (final locale in supportedLocales) {
      buf.writeln("import 'l10n_${locale.toLowerCase()}.dart';");
    }
    buf.writeln();

    for (final group in getterGroups) {
      buf.writeln("export 'getters/${group}_getters.dart';");
    }

    buf
      ..writeln()
      ..writeln('class AppLocalizations {')
      ..writeln('  AppLocalizations(this.locale);')
      ..writeln()
      ..writeln('  final String locale;')
      ..writeln()
      ..writeln('  static AppLocalizations of(BuildContext context) {')
      ..writeln('    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;')
      ..writeln('  }')
      ..writeln()
      ..writeln('  static const LocalizationsDelegate<AppLocalizations> delegate =')
      ..writeln('      _AppLocalizationsDelegate();')
      ..writeln()
      ..writeln('  static const List<Locale> supportedLocales = [');

    for (final locale in supportedLocales) {
      buf.writeln("    Locale('$locale'),");
    }

    buf
      ..writeln('  ];')
      ..writeln()
      ..writeln('  static final Map<String, Map<String, String>> _maps = {');

    for (final locale in supportedLocales) {
      buf.writeln("    '$locale': l10n${toPascalCase(locale)},");
    }

    buf
      ..writeln('  };')
      ..writeln()
      ..writeln('  Map<String, String> get _map =>')
      ..writeln("      _maps[locale] ?? _maps['$defaultLocale'] ?? {};")
      ..writeln()
      ..writeln("  String translate(String key) => _map[key] ?? key;")
      ..writeln('}')
      ..writeln()
      ..writeln('class _AppLocalizationsDelegate')
      ..writeln('    extends LocalizationsDelegate<AppLocalizations> {')
      ..writeln('  const _AppLocalizationsDelegate();')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  bool isSupported(Locale locale) =>')
      ..writeln(
        '      [${supportedLocales.map((l) => "'$l'").join(', ')}]'
        '.contains(locale.languageCode);',
      )
      ..writeln()
      ..writeln('  @override')
      ..writeln('  Future<AppLocalizations> load(Locale locale) async {')
      ..writeln('    return AppLocalizations(locale.languageCode);')
      ..writeln('  }')
      ..writeln()
      ..writeln('  @override')
      ..writeln('  bool shouldReload(_AppLocalizationsDelegate old) => false;')
      ..writeln('}')
      ..writeln()
      ..writeln('extension AppLocalizationsX on BuildContext {')
      ..writeln('  AppLocalizations get lang => AppLocalizations.of(this);')
      ..writeln('}');

    return buf.toString();
  }

  // ─── Helpers ────────────────────────────────────────────────────────────────

  List<String> _extractParams(String value) {
    return RegExp(r'\{(\w+)\}')
        .allMatches(value)
        .map((m) => m.group(1)!)
        .toList();
  }

  String _paramType(String param) {
    const intParams = {'count', 'total', 'amount', 'quantity', 'number'};
    return intParams.contains(param) ? 'int' : 'String';
  }

  String _keyToVar(String key) {
    final parts = key.split(RegExp(r'[_\-\s]+'));
    if (parts.isEmpty) return key;
    return parts.first.toLowerCase() + parts.skip(1).map(capitalize).join('');
  }
}
