import 'dart:io';
import '../utils/string_utils.dart';

class PageGenerator {
  /// Generate page structure using MagicCubit + MagicStatePage.
  ///
  /// [name] — page name (e.g., 'login', 'product_detail')
  /// [outputDir] — e.g., 'lib/features/auth'
  /// [pathParams] — path parameter names
  /// [queryParams] — query parameter names
  Future<List<String>> generate({
    required String name,
    required String outputDir,
    List<String> pathParams = const [],
    List<String> queryParams = const [],
  }) async {
    final pascal = toPascalCase(name);
    final snake = toSnakeCase(pascal);
    final normalizedOut = outputDir.endsWith('/')
        ? outputDir.substring(0, outputDir.length - 1)
        : outputDir;
    final featureDir = '$normalizedOut/$snake';
    final generated = <String>[];

    // ── Presentation layer ────────────────────────────────────────────────
    final statePath = '$featureDir/presentation/cubit/${snake}_state.dart';
    final cubitPath = '$featureDir/presentation/cubit/${snake}_cubit.dart';
    final pagePath = '$featureDir/presentation/pages/${snake}_page.dart';
    final widgetsGitkeep = '$featureDir/presentation/widgets/.gitkeep';

    _writeFile(statePath, _stateTemplate(pascal));
    _writeFile(cubitPath, _cubitTemplate(pascal, snake));
    _writeFile(pagePath, _pageTemplate(pascal, snake, pathParams, queryParams));
    _writeFileIfMissing(widgetsGitkeep, '');

    generated.addAll([statePath, cubitPath, pagePath, widgetsGitkeep]);
    return generated;
  }

  String _pageTemplate(
    String pascal,
    String snake,
    List<String> pathParams,
    List<String> queryParams,
  ) {
    final allParams = [...pathParams, ...queryParams];
    final hasParams = allParams.isNotEmpty;

    final constructorParams = hasParams
        ? allParams.map((p) {
            final isQuery = queryParams.contains(p);
            return isQuery ? 'this.$p' : 'required this.$p';
          }).join(', ')
        : '';

    final fieldDeclarations = hasParams
        ? allParams.map((p) {
            final isQuery = queryParams.contains(p);
            return isQuery
                ? '  final String? $p;'
                : '  final String $p;';
          }).join('\n')
        : '';

    final constructorLine = hasParams
        ? '  const ${pascal}Page({super.key, $constructorParams});'
        : '  const ${pascal}Page({super.key});';

    return '''
// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import '../../../../../core/base/magic_state_page.dart';
import '../../../../../core/dependency_injection/injector.dart';
import '../cubit/${snake}_cubit.dart';
import '../cubit/${snake}_state.dart';

class ${pascal}Page extends StatefulWidget {
${fieldDeclarations.isNotEmpty ? '$fieldDeclarations\n' : ''}$constructorLine

  @override
  State<${pascal}Page> createState() => _${pascal}PageState();
}

class _${pascal}PageState extends State<${pascal}Page>
    with MagicStatePage<${pascal}Page, ${pascal}Cubit, ${pascal}StateCubit> {
  @override
  ${pascal}Cubit createCubit() => getIt<${pascal}Cubit>();

  @override
  Widget buildPage(BuildContext context, ${pascal}StateCubit state) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('$pascal'),
      ),
      body: const Center(
        child: Text('// TODO: Implement ${snake.replaceAll('_', ' ')} UI'),
      ),
    );
  }
}
''';
  }

  String _stateTemplate(String pascal) => '''
// GENERATED BY MAGICKIT CLI

import 'package:equatable/equatable.dart';

class ${pascal}StateCubit extends Equatable {
  const ${pascal}StateCubit();

  ${pascal}StateCubit copyWith() => const ${pascal}StateCubit();

  @override
  List<Object?> get props => [];
}
''';

  String _cubitTemplate(String pascal, String snake) => '''
// GENERATED BY MAGICKIT CLI

import '../../../../../core/base/magic_cubit.dart';
import '${snake}_state.dart';

class ${pascal}Cubit extends MagicCubit<${pascal}StateCubit> {
  ${pascal}Cubit() : super(const ${pascal}StateCubit());
}
''';

  void _writeFile(String path, String content) {
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
  }

  void _writeFileIfMissing(String path, String content) {
    final file = File(path);
    file.parent.createSync(recursive: true);
    if (!file.existsSync()) {
      file.writeAsStringSync(content);
    }
  }
}
