// ignore_for_file: unnecessary_brace_in_string_interps
import 'dart:io';
import '../utils/string_utils.dart';

class PageGenerator {
  /// Generate semua file clean architecture untuk satu feature.
  ///
  /// [withBloc] — tambahkan Bloc layer (untuk complex case)
  Future<List<String>> generate({
    required String name,
    required String outputDir,
    bool withBloc = false,
  }) async {
    final pascal = toPascalCase(name);
    final snake = toSnakeCase(pascal);
    final camel = _toCamel(snake);
    final normalizedOut = outputDir.endsWith('/')
        ? outputDir.substring(0, outputDir.length - 1)
        : outputDir;
    final featureDir = '$normalizedOut/$snake';
    final generated = <String>[];

    // ── Data & Domain layer — hanya .gitkeep ─────────────────────────────────
    final gitkeepDirs = [
      '$featureDir/data/datasources',
      '$featureDir/data/models',
      '$featureDir/data/repositories',
      '$featureDir/domain/entities',
      '$featureDir/domain/repositories',
      '$featureDir/domain/usecases',
    ];
    for (final dir in gitkeepDirs) {
      final file = File('$dir/.gitkeep');
      file.parent.createSync(recursive: true);
      file.writeAsStringSync('');
      generated.add('$dir/.gitkeep');
    }

    // ── Presentation layer ────────────────────────────────────────────────────
    final presentationFiles = <String, String>{
      '$featureDir/presentation/cubit/${snake}_state.dart':
          _stateTemplate(pascal),
      '$featureDir/presentation/cubit/${snake}_cubit.dart':
          withBloc
              ? _cubitWithBlocTemplate(pascal, snake, camel)
              : _cubitTemplate(pascal, snake),
      '$featureDir/presentation/pages/${snake}_page.dart':
          _pageTemplate(pascal, snake),
    };

    if (withBloc) {
      presentationFiles.addAll({
        '$featureDir/presentation/bloc/${snake}_bloc.dart':
            _blocTemplate(pascal, snake),
        '$featureDir/presentation/bloc/${snake}_event.dart':
            _blocEventTemplate(pascal),
        '$featureDir/presentation/bloc/${snake}_state.dart':
            _blocStateTemplate(pascal),
      });
    }

    // ── Dependency injection ──────────────────────────────────────────────────
    presentationFiles['$featureDir/dependency_injection/${snake}_dependency_injection.dart'] =
        withBloc
            ? _diWithBlocTemplate(pascal, snake, camel)
            : _diTemplate(pascal, snake);

    for (final entry in presentationFiles.entries) {
      final file = File(entry.key);
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(entry.value);
      generated.add(entry.key);
    }

    return generated;
  }

  // ─── Templates ─────────────────────────────────────────────────────────────

  String _stateTemplate(String pascal) => '''
// GENERATED BY MAGICKIT CLI

class ${pascal}StateCubit {
  final bool isLoading;
  final String? error;

  const ${pascal}StateCubit({
    this.isLoading = false,
    this.error,
  });

  bool get isError => error != null;

  ${pascal}StateCubit copyWith({
    bool? isLoading,
    String? error,
  }) {
    return ${pascal}StateCubit(
      isLoading: isLoading ?? this.isLoading,
      error: error,
    );
  }
}
''';

  String _cubitTemplate(String pascal, String snake) => '''
// GENERATED BY MAGICKIT CLI

import '../../../../core/base/magic_cubit.dart';
import '${snake}_state.dart';

class ${pascal}Cubit extends MagicCubit<${pascal}StateCubit> {
  ${pascal}Cubit() : super(const ${pascal}StateCubit());

  @override
  void onInit() {
    // TODO: Initial setup
  }
}
''';

  String _cubitWithBlocTemplate(
    String pascal,
    String snake,
    String camel,
  ) =>
      '''
// GENERATED BY MAGICKIT CLI

import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../../core/base/magic_cubit.dart';
import '../bloc/${snake}_bloc.dart';
import '${snake}_state.dart';

class ${pascal}Cubit extends MagicCubit<${pascal}StateCubit> {
  final ${pascal}Bloc ${camel}Bloc;

  ${pascal}Cubit({required this.${camel}Bloc})
      : super(const ${pascal}StateCubit());

  @override
  List<BlocProvider> get blocProviders => [
        BlocProvider<${pascal}Bloc>.value(value: ${camel}Bloc),
      ];

  @override
  List<BlocListener> Function(BuildContext context)? get blocListeners =>
      (context) => [
            BlocListener<${pascal}Bloc, ${pascal}State>(
              listener: (_, state) => _handle${pascal}Response(state),
            ),
          ];

  @override
  void onDispose() {
    ${camel}Bloc.close();
  }

  @override
  void onInit() {
    // TODO: Initial setup
  }

  // ─── UI Logic ───────────────────────────────────────────────────────────────

  // ─── Data Logic ─────────────────────────────────────────────────────────────

  void fetch() {
    emit(state.copyWith(isLoading: true));
    ${camel}Bloc.add(const Fetch${pascal}());
  }

  void _handle${pascal}Response(${pascal}State blocState) {
    if (blocState is ${pascal}Success) {
      emit(state.copyWith(isLoading: false));
    }
    if (blocState is ${pascal}Failed) {
      emit(state.copyWith(
        isLoading: false,
        error: blocState.failure.toString(),
      ));
    }
  }
}
''';

  String _pageTemplate(String pascal, String snake) => '''
// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import '../../../../core/base/magic_state_page.dart';
import '../../../../core/dependency_injection/injection.dart';
import '../cubit/${snake}_cubit.dart';
import '../cubit/${snake}_state.dart';

class ${pascal}Page extends StatefulWidget {
  const ${pascal}Page({super.key});

  @override
  State<${pascal}Page> createState() => _${pascal}PageState();
}

class _${pascal}PageState extends State<${pascal}Page>
    with MagicStatePage<${pascal}Page, ${pascal}Cubit, ${pascal}StateCubit> {
  @override
  ${pascal}Cubit createCubit() => sl();

  @override
  Widget buildPage(BuildContext context, ${pascal}StateCubit state) {
    return Scaffold(
      body: state.isLoading
          ? const Center(child: CircularProgressIndicator())
          : const Center(child: Text('${pascal} Page')),
    );
  }
}
''';

  String _diTemplate(String pascal, String snake) => '''
// GENERATED BY MAGICKIT CLI

import 'package:get_it/get_it.dart';
import '../presentation/cubit/${snake}_cubit.dart';

void register${pascal}(GetIt sl) {
  // TODO: Register datasource, repository, usecase saat sudah diisi
  // sl.registerFactory(() => ${pascal}RemoteDatasourceImpl(client: sl()));
  // sl.registerFactory(() => ${pascal}RepositoryImpl(datasource: sl()));
  // sl.registerFactory(() => ${pascal}Usecase(repository: sl()));

  sl.registerFactory(() => ${pascal}Cubit());
}
''';

  String _diWithBlocTemplate(String pascal, String snake, String camel) => '''
// GENERATED BY MAGICKIT CLI

import 'package:get_it/get_it.dart';
import '../presentation/cubit/${snake}_cubit.dart';
import '../presentation/bloc/${snake}_bloc.dart';

void register${pascal}(GetIt sl) {
  // TODO: Register datasource, repository, usecase saat sudah diisi
  // sl.registerFactory(() => ${pascal}RemoteDatasourceImpl(client: sl()));
  // sl.registerFactory(() => ${pascal}RepositoryImpl(datasource: sl()));
  // sl.registerFactory(() => Fetch${pascal}Usecase(repository: sl()));

  sl.registerFactory(() => ${pascal}Bloc());
  sl.registerFactory(() => ${pascal}Cubit(${camel}Bloc: sl()));
}
''';

  String _blocTemplate(String pascal, String snake) => '''
// GENERATED BY MAGICKIT CLI

import 'package:flutter_bloc/flutter_bloc.dart';
import '${snake}_event.dart';
import '${snake}_state.dart';

class ${pascal}Bloc extends Bloc<${pascal}Event, ${pascal}State> {
  ${pascal}Bloc() : super(const ${pascal}Initial()) {
    on<Fetch${pascal}>(_onFetch);
  }

  Future<void> _onFetch(
    Fetch${pascal} event,
    Emitter<${pascal}State> emit,
  ) async {
    emit(const ${pascal}Loading());
    try {
      // TODO: call usecase
      emit(const ${pascal}Success());
    } catch (e) {
      emit(${pascal}Failed(e));
    }
  }
}
''';

  String _blocEventTemplate(String pascal) => '''
// GENERATED BY MAGICKIT CLI

abstract class ${pascal}Event {
  const ${pascal}Event();
}

class Fetch${pascal} extends ${pascal}Event {
  const Fetch${pascal}();
}
''';

  String _blocStateTemplate(String pascal) => '''
// GENERATED BY MAGICKIT CLI

abstract class ${pascal}State {
  const ${pascal}State();
}

class ${pascal}Initial extends ${pascal}State {
  const ${pascal}Initial();
}

class ${pascal}Loading extends ${pascal}State {
  const ${pascal}Loading();
}

class ${pascal}Success extends ${pascal}State {
  const ${pascal}Success();
}

class ${pascal}Failed extends ${pascal}State {
  final Object failure;
  const ${pascal}Failed(this.failure);
}
''';

  // ─── Helpers ────────────────────────────────────────────────────────────────

  String _toCamel(String snake) {
    final parts = snake.split('_');
    if (parts.isEmpty) return snake;
    return parts.first +
        parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join('');
  }
}
