class ComponentInfo {
  final String name;
  final String category;
  final String useCase;
  final List<String> visualKeywords;
  final String? importPath;

  const ComponentInfo({
    required this.name,
    required this.category,
    required this.useCase,
    required this.visualKeywords,
    this.importPath,
  });
}

class RegistryGenerator {
  static final _annotationPattern = RegExp(
    r'\{@magickit\}(.*?)\{@end\}',
    dotAll: true,
  );

  /// Parse Dart source file content dan extract semua komponen yang diannotasi.
  List<ComponentInfo> parseSource(String content) {
    final results = <ComponentInfo>[];

    for (final match in _annotationPattern.allMatches(content)) {
      final block = match.group(1) ?? '';
      final info = _parseAnnotationBlock(block);
      if (info != null) results.add(info);
    }

    return results;
  }

  ComponentInfo? _parseAnnotationBlock(String block) {
    final lines = block
        .split('\n')
        .map((l) => l.trim())
        .where((l) => l.startsWith('///'))
        .map((l) => l.substring(3).trim())
        .where((l) => l.isNotEmpty);

    String? name, category, useCase;
    List<String> visualKeywords = [];

    for (final line in lines) {
      if (line.startsWith('name:')) {
        name = line.substring(5).trim();
      } else if (line.startsWith('category:')) {
        category = line.substring(9).trim();
      } else if (line.startsWith('use_case:')) {
        useCase = line.substring(9).trim();
      } else if (line.startsWith('visual_keywords:')) {
        final raw = line.substring(16).trim();
        visualKeywords = raw.split(',').map((k) => k.trim()).toList();
      }
    }

    if (name == null || category == null) return null;

    return ComponentInfo(
      name: name,
      category: category,
      useCase: useCase ?? '',
      visualKeywords: visualKeywords,
    );
  }

  /// Generate component_registry.yaml dari list ComponentInfo.
  String generateYaml(
    List<ComponentInfo> components, {
    String importPath = 'package:magickit/magickit.dart',
  }) {
    final buffer = StringBuffer()
      ..writeln('# MagicKit Component Registry')
      ..writeln('# Generated by: magickit registry')
      ..writeln('# Do not edit — run `magickit registry` to regenerate.')
      ..writeln()
      ..writeln('components:');

    for (final c in components) {
      final keywords =
          c.visualKeywords.map((k) => '"$k"').join(', ');
      buffer
        ..writeln('  - name: ${c.name}')
        ..writeln('    category: ${c.category}')
        ..writeln("    import: '$importPath'")
        ..writeln("    use_case: '${c.useCase}'")
        ..writeln('    visual_keywords: [$keywords]');
    }

    return buffer.toString();
  }

  /// Generate AI context bundle — ringkasan kompak untuk prompt AI slicing.
  String generateAiBundle(List<ComponentInfo> components) {
    final grouped = <String, List<ComponentInfo>>{};
    for (final c in components) {
      grouped.putIfAbsent(c.category.toUpperCase(), () => []).add(c);
    }

    final buffer = StringBuffer()
      ..writeln('Available MagicKit Components:')
      ..writeln();

    // Sort categories: ATOM, MOLECULE, ORGANISM
    final order = ['ATOM', 'MOLECULE', 'ORGANISM'];
    final keys = grouped.keys.toList()
      ..sort((a, b) {
        final ai = order.indexOf(a);
        final bi = order.indexOf(b);
        return ai == -1 && bi == -1
            ? a.compareTo(b)
            : ai == -1
                ? 1
                : bi == -1
                    ? -1
                    : ai.compareTo(bi);
      });

    for (final key in keys) {
      buffer.writeln('${key}S:');
      for (final c in grouped[key]!) {
        final keywords = c.visualKeywords.join(', ');
        buffer.writeln('- ${c.name} → ${c.useCase} [$keywords]');
      }
      buffer.writeln();
    }

    buffer
      ..writeln('Rules untuk AI:')
      ..writeln(
        '1. SELALU gunakan komponen MagicKit yang tersedia jika cocok',
      )
      ..writeln(
        '2. Jika tidak ada komponen yang cocok, buat widget baru dengan prefix "Custom"',
      )
      ..writeln(
        '3. Gunakan MagicTheme tokens untuk warna, spacing, typography',
      )
      ..writeln(
        "4. Jangan hardcode values — selalu pakai theme tokens",
      );

    return buffer.toString();
  }
}
