// ignore_for_file: unnecessary_brace_in_string_interps
import 'dart:io';
import 'package:args/command_runner.dart';
import '../generators/route_generator.dart';
import '../utils/logger.dart';
import '../utils/string_utils.dart';

class KickstartCommand extends Command<void> {
  @override
  String get name => 'kickstart';

  @override
  String get description =>
      'Generate starter app: splash, onboarding, login, main navigation.';

  @override
  String get invocation => 'magickit kickstart';

  @override
  Future<void> run() async {
    logger.info('');
    logger.info('MagicKit Kickstart!');
    logger.info('');

    // ── Prerequisite check ────────────────────────────────────────────────────
    logger.info('Checking prerequisites...');
    if (!File('lib/core/dependency_injection/injector.dart').existsSync()) {
      logger.err(
          "magickit init not detected.\n   Run 'magickit init' first.");
      return;
    }
    logger.info('  magickit init detected');
    logger.info('');

    // ── Create feature route groups ───────────────────────────────────────────
    logger.info('Creating features...');
    final routeGen = RouteGenerator();

    for (final feature in ['startup', 'auth', 'main']) {
      final featureFiles = routeGen.generateFeatureRouteFiles(feature);
      for (final entry in featureFiles.entries) {
        _writeFile(entry.key, entry.value);
      }
      routeGen.updateCoreForFeature(feature);
    }

    // ── Create page structures (gitkeep + DI) ─────────────────────────────────
    final pages = [
      ('startup', 'splash'),
      ('startup', 'onboarding'),
      ('auth', 'login'),
      ('main', 'main_navigation'),
      ('main', 'home'),
      ('main', 'profile'),
    ];

    for (final (feature, page) in pages) {
      _createPageStructure(feature, page);
    }

    // ── Register all pages in injector.dart ──────────────────────────────────
    _updateAllInjections();

    // ── Overwrite with customized implementations ─────────────────────────────
    logger.info('');
    logger.info('Customizing template...');

    _writeStartupRouteNames();
    _writeStartupRoutes();
    _writeStartupRouteExtensions();
    _writeAuthRouteNames();
    _writeAuthRoutes();
    _writeAuthRouteExtensions();
    _writeMainRouteNames();
    _writeMainRoutes();
    _writeMainRouteExtensions();

    _writeSplashCubit();
    _writeSplashState();
    _writeSplashPage();

    _writeOnboardingCubit();
    _writeOnboardingState();
    _writeOnboardingPage();

    _writeLoginCubit();
    _writeLoginState();
    _writeLoginPage();

    _writeMainNavigationCubit();
    _writeMainNavigationState();
    _writeMainNavigationPage();

    _writeHomeCubit();
    _writeHomeState();
    _writeHomePage();

    _writeProfileCubit();
    _writeProfileState();
    _writeProfilePage();

    _writeMainDart();

    logger.success('main.dart updated');
    logger.success('Splash → auto navigate');
    logger.success('Onboarding → 3 slides');
    logger.success('Login → form with validation');
    logger.success('Main → bottom navigation (home + profile)');
    logger.success('Profile → logout with dialog');

    logger.info('');
    logger.success('Your app is ready to run!');
    logger.info('   → flutter run');
    logger.info('   → Demo login: test@mail.com / 123456');
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  void _writeFile(String path, String content) {
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
  }

  void _createPageStructure(String feature, String page) {
    final pascal = toPascalCase(page);
    final snake = toSnakeCase(pascal);
    final featureDir = 'lib/features/$feature/$snake';

    // .gitkeep dirs (skip for main_navigation which has no data/domain layer)
    if (snake != 'main_navigation') {
      for (final dir in [
        '$featureDir/data/datasources',
        '$featureDir/data/models',
        '$featureDir/data/repositories',
        '$featureDir/domain/entities',
        '$featureDir/domain/repositories',
        '$featureDir/domain/usecases',
      ]) {
        final f = File('$dir/.gitkeep');
        f.parent.createSync(recursive: true);
        f.writeAsStringSync('');
      }
    }

    // Ensure presentation dirs
    for (final dir in [
      '$featureDir/presentation/cubit',
      '$featureDir/presentation/pages',
      '$featureDir/dependency_injection',
    ]) {
      Directory(dir).createSync(recursive: true);
    }

    // DI file
    _writeFile(
      '$featureDir/dependency_injection/${snake}_dependency_injection.dart',
      '// GENERATED BY MAGICKIT CLI\n\n'
      "import 'package:get_it/get_it.dart';\n"
      "import '../presentation/cubit/${snake}_cubit.dart';\n\n"
      'void register${pascal}(GetIt getIt) {\n'
      '  getIt.registerFactory(() => ${pascal}Cubit());\n'
      '}\n',
    );

    logger.info('  Page: $feature/$page');
  }

  void _updateAllInjections() {
    final injectorFile =
        File('lib/core/dependency_injection/injector.dart');
    if (!injectorFile.existsSync()) return;

    var content = injectorFile.readAsStringSync();

    final entries = [
      ('startup/splash', 'splash', 'Splash'),
      ('startup/onboarding', 'onboarding', 'Onboarding'),
      ('auth/login', 'login', 'Login'),
      ('main/main_navigation', 'main_navigation', 'MainNavigation'),
      ('main/home', 'home', 'Home'),
      ('main/profile', 'profile', 'Profile'),
    ];

    for (final (featurePath, snake, pascal) in entries) {
      final importPath =
          '../../features/$featurePath/dependency_injection/${snake}_dependency_injection.dart';
      final importLine = "import '$importPath';";
      final registerLine = '  register$pascal(getIt);';

      if (!content.contains(importLine) &&
          content.contains('// MAGICKIT:IMPORT')) {
        content = content.replaceFirst(
          '// MAGICKIT:IMPORT',
          '$importLine\n// MAGICKIT:IMPORT',
        );
      }

      if (!content.contains(registerLine) &&
          content.contains('// MAGICKIT:INJECTOR')) {
        content = content.replaceFirst(
          '// MAGICKIT:INJECTOR',
          '$registerLine\n  // MAGICKIT:INJECTOR',
        );
      }
    }

    injectorFile.writeAsStringSync(content);
  }

  // ── Feature Route Files ───────────────────────────────────────────────────

  void _writeStartupRouteNames() {
    _writeFile(
      'lib/features/startup/routes/startup_route_names.dart',
      '''// GENERATED BY MAGICKIT CLI

class StartupRouteName {
  StartupRouteName._();

  static const String splash = 'startup-splash';
  static const String onboarding = 'startup-onboarding';

  static const String splashPath = '/';
  static const String onboardingPath = '/onboarding';
}
''',
    );
  }

  void _writeStartupRoutes() {
    _writeFile(
      'lib/features/startup/routes/startup_routes.dart',
      '''// GENERATED BY MAGICKIT CLI

import 'package:go_router/go_router.dart';
import 'startup_route_names.dart';
import '../splash/presentation/pages/splash_page.dart';
import '../onboarding/presentation/pages/onboarding_page.dart';

final startupRoutes = <RouteBase>[
  GoRoute(
    name: StartupRouteName.splash,
    path: StartupRouteName.splashPath,
    builder: (context, state) => const SplashPage(),
  ),
  GoRoute(
    name: StartupRouteName.onboarding,
    path: StartupRouteName.onboardingPath,
    builder: (context, state) => const OnboardingPage(),
  ),
];
''',
    );
  }

  void _writeStartupRouteExtensions() {
    _writeFile(
      'lib/features/startup/routes/startup_route_extensions.dart',
      '''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'startup_route_names.dart';

extension StartupRouteExtensions on BuildContext {
  void pushSplash() => pushNamed(StartupRouteName.splash);
  void pushOnboarding() => pushNamed(StartupRouteName.onboarding);
}
''',
    );
  }

  void _writeAuthRouteNames() {
    _writeFile(
      'lib/features/auth/routes/auth_route_names.dart',
      '''// GENERATED BY MAGICKIT CLI

class AuthRouteName {
  AuthRouteName._();

  static const String login = 'auth-login';

  static const String loginPath = '/auth/login';
}
''',
    );
  }

  void _writeAuthRoutes() {
    _writeFile(
      'lib/features/auth/routes/auth_routes.dart',
      '''// GENERATED BY MAGICKIT CLI

import 'package:go_router/go_router.dart';
import 'auth_route_names.dart';
import '../login/presentation/pages/login_page.dart';

final authRoutes = <RouteBase>[
  GoRoute(
    name: AuthRouteName.login,
    path: AuthRouteName.loginPath,
    builder: (context, state) => const LoginPage(),
  ),
];
''',
    );
  }

  void _writeAuthRouteExtensions() {
    _writeFile(
      'lib/features/auth/routes/auth_route_extensions.dart',
      '''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'auth_route_names.dart';

extension AuthRouteExtensions on BuildContext {
  void pushLogin() => pushNamed(AuthRouteName.login);
}
''',
    );
  }

  void _writeMainRouteNames() {
    _writeFile(
      'lib/features/main/routes/main_route_names.dart',
      '''// GENERATED BY MAGICKIT CLI

class MainRouteName {
  MainRouteName._();

  static const String mainNavigation = 'main-navigation';
  static const String home = 'main-home';
  static const String profile = 'main-profile';

  static const String mainNavigationPath = '/main';
  static const String homePath = '/main/home';
  static const String profilePath = '/main/profile';
}
''',
    );
  }

  void _writeMainRoutes() {
    _writeFile(
      'lib/features/main/routes/main_routes.dart',
      '''// GENERATED BY MAGICKIT CLI

import 'package:go_router/go_router.dart';
import 'main_route_names.dart';
import '../main_navigation/presentation/pages/main_navigation_page.dart';
import '../home/presentation/pages/home_page.dart';
import '../profile/presentation/pages/profile_page.dart';

final mainRoutes = <RouteBase>[
  ShellRoute(
    builder: (context, state, child) => MainNavigationPage(child: child),
    routes: [
      GoRoute(
        name: MainRouteName.home,
        path: MainRouteName.homePath,
        builder: (context, state) => const HomePage(),
      ),
      GoRoute(
        name: MainRouteName.profile,
        path: MainRouteName.profilePath,
        builder: (context, state) => const ProfilePage(),
      ),
    ],
  ),
];
''',
    );
  }

  void _writeMainRouteExtensions() {
    _writeFile(
      'lib/features/main/routes/main_route_extensions.dart',
      '''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'main_route_names.dart';

extension MainRouteExtensions on BuildContext {
  void pushHome() => pushNamed(MainRouteName.home);
  void pushProfile() => pushNamed(MainRouteName.profile);
}
''',
    );
  }

  // ── Splash ────────────────────────────────────────────────────────────────

  void _writeSplashState() {
    _writeFile(
      'lib/features/startup/splash/presentation/cubit/splash_state.dart',
      '''// GENERATED BY MAGICKIT CLI

class SplashStateCubit {
  const SplashStateCubit();
}
''',
    );
  }

  void _writeSplashCubit() {
    _writeFile(
      'lib/features/startup/splash/presentation/cubit/splash_cubit.dart',
      '''// GENERATED BY MAGICKIT CLI

import '../../../../../core/base/magic_cubit.dart';
import '../../../../auth/routes/auth_route_names.dart';
import '../../../../main/routes/main_route_names.dart';
import '../../../routes/startup_route_names.dart';
import 'splash_state.dart';

class SplashCubit extends MagicCubit<SplashStateCubit> {
  SplashCubit() : super(const SplashStateCubit());

  void Function(String path)? _onNavigate;

  void setOnNavigate(void Function(String path) callback) {
    _onNavigate = callback;
  }

  @override
  void onReady() {
    _navigate();
  }

  Future<void> _navigate() async {
    await Future.delayed(const Duration(seconds: 2));

    // TODO: Cek dari local storage
    const hasSeenOnboarding = false;
    const isLoggedIn = false;

    if (!hasSeenOnboarding) {
      _onNavigate?.call(StartupRouteName.onboardingPath);
    } else if (!isLoggedIn) {
      _onNavigate?.call(AuthRouteName.loginPath);
    } else {
      _onNavigate?.call(MainRouteName.homePath);
    }
  }
}
''',
    );
  }

  void _writeSplashPage() {
    _writeFile(
      'lib/features/startup/splash/presentation/pages/splash_page.dart',
      r'''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:magickit/magickit.dart';
import '../../../../../core/base/magic_state_page.dart';
import '../../../../../core/dependency_injection/injector.dart';
import '../cubit/splash_cubit.dart';
import '../cubit/splash_state.dart';

class SplashPage extends StatefulWidget {
  const SplashPage({super.key});

  @override
  State<SplashPage> createState() => _SplashPageState();
}

class _SplashPageState extends State<SplashPage>
    with MagicStatePage<SplashPage, SplashCubit, SplashStateCubit> {
  @override
  SplashCubit createCubit() {
    final c = getIt<SplashCubit>();
    c.setOnNavigate((path) => context.go(path));
    return c;
  }

  @override
  Widget buildPage(BuildContext context, SplashStateCubit state) {
    final theme = MagicTheme.of(context);
    return Scaffold(
      backgroundColor: theme.colors.background,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            MagicImage(src: 'assets/images/logo.png', width: 120, height: 120),
            SizedBox(height: theme.spacing.lg),
            MagicText('MagicKit', style: theme.typography.heading1),
            SizedBox(height: theme.spacing.sm),
            MagicText(
              'Build Flutter Apps Faster',
              style: theme.typography.bodyMedium,
              color: theme.colors.onBackgroundSecondary,
            ),
            SizedBox(height: theme.spacing.xl),
            MagicShimmer(
              width: 48,
              height: 48,
              borderRadius: theme.radius.full,
            ),
          ],
        ),
      ),
    );
  }
}
''',
    );
  }

  // ── Onboarding ────────────────────────────────────────────────────────────

  void _writeOnboardingState() {
    _writeFile(
      'lib/features/startup/onboarding/presentation/cubit/onboarding_state.dart',
      '''// GENERATED BY MAGICKIT CLI

class OnboardingStateCubit {
  final int currentPage;
  const OnboardingStateCubit({this.currentPage = 0});

  OnboardingStateCubit copyWith({int? currentPage}) {
    return OnboardingStateCubit(
      currentPage: currentPage ?? this.currentPage,
    );
  }
}
''',
    );
  }

  void _writeOnboardingCubit() {
    _writeFile(
      'lib/features/startup/onboarding/presentation/cubit/onboarding_cubit.dart',
      '''// GENERATED BY MAGICKIT CLI

import '../../../../../core/base/magic_cubit.dart';
import 'onboarding_state.dart';

class OnboardingCubit extends MagicCubit<OnboardingStateCubit> {
  OnboardingCubit() : super(const OnboardingStateCubit());

  void setPage(int page) {
    emit(state.copyWith(currentPage: page));
  }
}
''',
    );
  }

  void _writeOnboardingPage() {
    _writeFile(
      'lib/features/startup/onboarding/presentation/pages/onboarding_page.dart',
      r'''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:magickit/magickit.dart';
import '../../../../../core/base/magic_state_page.dart';
import '../../../../../core/dependency_injection/injector.dart';
import '../../../../auth/routes/auth_route_names.dart';
import '../cubit/onboarding_cubit.dart';
import '../cubit/onboarding_state.dart';

class OnboardingPage extends StatefulWidget {
  const OnboardingPage({super.key});

  @override
  State<OnboardingPage> createState() => _OnboardingPageState();
}

class _OnboardingPageState extends State<OnboardingPage>
    with MagicStatePage<OnboardingPage, OnboardingCubit, OnboardingStateCubit> {
  final _pageController = PageController();

  @override
  OnboardingCubit createCubit() => getIt();

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget buildPage(BuildContext context, OnboardingStateCubit state) {
    final theme = MagicTheme.of(context);
    final slides = [
      _Slide(icon: Icons.star, title: 'Welcome', subtitle: 'Discover amazing features'),
      _Slide(icon: Icons.touch_app, title: 'Easy', subtitle: 'Simple and intuitive'),
      _Slide(icon: Icons.rocket_launch, title: 'Ready', subtitle: "Let's get started"),
    ];

    return Scaffold(
      backgroundColor: theme.colors.background,
      body: SafeArea(
        child: Column(
          children: [
            Expanded(
              child: PageView.builder(
                controller: _pageController,
                onPageChanged: cubit.setPage,
                itemCount: slides.length,
                itemBuilder: (context, index) {
                  final slide = slides[index];
                  return Padding(
                    padding: EdgeInsets.all(theme.spacing.xl),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        MagicIcon(
                          icon: slide.icon,
                          size: 80,
                          color: theme.colors.primary,
                        ),
                        SizedBox(height: theme.spacing.lg),
                        MagicText(slide.title, style: theme.typography.heading2),
                        SizedBox(height: theme.spacing.sm),
                        MagicText(
                          slide.subtitle,
                          style: theme.typography.bodyMedium,
                          color: theme.colors.onBackgroundSecondary,
                          textAlign: TextAlign.center,
                        ),
                      ],
                    ),
                  );
                },
              ),
            ),
            Padding(
              padding: EdgeInsets.all(theme.spacing.lg),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Row(
                    children: List.generate(
                      slides.length,
                      (i) => Container(
                        width: 8,
                        height: 8,
                        margin: EdgeInsets.only(right: theme.spacing.xs),
                        decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: state.currentPage == i
                              ? theme.colors.primary
                              : theme.colors.onBackgroundSecondary
                                  .withOpacity(0.3),
                        ),
                      ),
                    ),
                  ),
                  MagicButton(
                    label: state.currentPage == slides.length - 1
                        ? 'Get Started'
                        : 'Next',
                    onPressed: () {
                      if (state.currentPage == slides.length - 1) {
                        context.go(AuthRouteName.loginPath);
                      } else {
                        _pageController.nextPage(
                          duration: const Duration(milliseconds: 300),
                          curve: Curves.easeInOut,
                        );
                      }
                    },
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _Slide {
  final IconData icon;
  final String title;
  final String subtitle;
  const _Slide({
    required this.icon,
    required this.title,
    required this.subtitle,
  });
}
''',
    );
  }

  // ── Login ─────────────────────────────────────────────────────────────────

  void _writeLoginState() {
    _writeFile(
      'lib/features/auth/login/presentation/cubit/login_state.dart',
      '''// GENERATED BY MAGICKIT CLI

class LoginStateCubit {
  final bool isLoading;
  final bool obscurePassword;
  final String? error;

  const LoginStateCubit({
    this.isLoading = false,
    this.obscurePassword = true,
    this.error,
  });

  LoginStateCubit copyWith({
    bool? isLoading,
    bool? obscurePassword,
    String? error,
  }) {
    return LoginStateCubit(
      isLoading: isLoading ?? this.isLoading,
      obscurePassword: obscurePassword ?? this.obscurePassword,
      error: error,
    );
  }
}
''',
    );
  }

  void _writeLoginCubit() {
    _writeFile(
      'lib/features/auth/login/presentation/cubit/login_cubit.dart',
      '''// GENERATED BY MAGICKIT CLI

import '../../../../../core/base/magic_cubit.dart';
import 'login_state.dart';

class LoginCubit extends MagicCubit<LoginStateCubit> {
  LoginCubit() : super(const LoginStateCubit());

  void Function()? _onLoginSuccess;

  void setOnLoginSuccess(void Function() callback) {
    _onLoginSuccess = callback;
  }

  void toggleObscurePassword() {
    emit(state.copyWith(obscurePassword: !state.obscurePassword));
  }

  String? validateEmail(String? value) {
    if (value == null || value.isEmpty) return 'Email tidak boleh kosong';
    if (!value.contains('@')) return 'Format email tidak valid';
    return null;
  }

  String? validatePassword(String? value) {
    if (value == null || value.isEmpty) return 'Password tidak boleh kosong';
    if (value.length < 6) return 'Password minimal 6 karakter';
    return null;
  }

  Future<void> login({
    required String email,
    required String password,
  }) async {
    emit(state.copyWith(isLoading: true, error: null));
    await Future.delayed(const Duration(seconds: 2));
    if (email == 'test@mail.com' && password == '123456') {
      emit(state.copyWith(isLoading: false));
      _onLoginSuccess?.call();
    } else {
      emit(state.copyWith(
        isLoading: false,
        error: 'Email atau password salah',
      ));
    }
  }
}
''',
    );
  }

  void _writeLoginPage() {
    _writeFile(
      'lib/features/auth/login/presentation/pages/login_page.dart',
      r'''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:magickit/magickit.dart';
import '../../../../../core/base/magic_state_page.dart';
import '../../../../../core/dependency_injection/injector.dart';
import '../../../../main/routes/main_route_names.dart';
import '../cubit/login_cubit.dart';
import '../cubit/login_state.dart';

class LoginPage extends StatefulWidget {
  const LoginPage({super.key});

  @override
  State<LoginPage> createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage>
    with MagicStatePage<LoginPage, LoginCubit, LoginStateCubit> {
  final _formKey = GlobalKey<FormState>();
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();

  @override
  LoginCubit createCubit() {
    final c = getIt<LoginCubit>();
    c.setOnLoginSuccess(() => context.go(MainRouteName.homePath));
    return c;
  }

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  @override
  Widget buildPage(BuildContext context, LoginStateCubit state) {
    final theme = MagicTheme.of(context);
    return Scaffold(
      backgroundColor: theme.colors.background,
      body: SafeArea(
        child: Padding(
          padding: EdgeInsets.all(theme.spacing.lg),
          child: MagicForm(
            formKey: _formKey,
            children: [
              const Spacer(),
              MagicText(
                'Welcome Back',
                style: theme.typography.heading1,
                textAlign: TextAlign.center,
              ),
              SizedBox(height: theme.spacing.xs),
              MagicText(
                'Login to continue',
                style: theme.typography.bodyMedium,
                color: theme.colors.onBackgroundSecondary,
                textAlign: TextAlign.center,
              ),
              SizedBox(height: theme.spacing.xxl),
              MagicFormField(
                label: 'Email',
                child: MagicInput(
                  controller: _emailController,
                  hint: 'Enter your email',
                  keyboardType: TextInputType.emailAddress,
                  prefixIcon: Icons.email_outlined,
                  validator: cubit.validateEmail,
                ),
              ),
              SizedBox(height: theme.spacing.md),
              MagicFormField(
                label: 'Password',
                child: MagicInput(
                  controller: _passwordController,
                  hint: 'Enter your password',
                  obscureText: state.obscurePassword,
                  prefixIcon: Icons.lock_outlined,
                  suffixIcon: state.obscurePassword
                      ? Icons.visibility_off
                      : Icons.visibility,
                  onSuffixIconTap: cubit.toggleObscurePassword,
                  validator: cubit.validatePassword,
                ),
              ),
              if (state.error != null) ...[
                SizedBox(height: theme.spacing.sm),
                MagicText(
                  state.error!,
                  style: theme.typography.bodySmall,
                  color: theme.colors.error,
                  textAlign: TextAlign.center,
                ),
              ],
              SizedBox(height: theme.spacing.lg),
              MagicButton(
                label: 'Login',
                onPressed: state.isLoading
                    ? null
                    : () {
                        if (_formKey.currentState!.validate()) {
                          cubit.login(
                            email: _emailController.text,
                            password: _passwordController.text,
                          );
                        }
                      },
                isLoading: state.isLoading,
                variant: MagicButtonVariant.primary,
                size: MagicButtonSize.large,
              ),
              SizedBox(height: theme.spacing.md),
              MagicText(
                'Demo: test@mail.com / 123456',
                style: theme.typography.caption,
                color: theme.colors.onBackgroundSecondary,
                textAlign: TextAlign.center,
              ),
              const Spacer(),
            ],
          ),
        ),
      ),
    );
  }
}
''',
    );
  }

  // ── Main Navigation ───────────────────────────────────────────────────────

  void _writeMainNavigationState() {
    _writeFile(
      'lib/features/main/main_navigation/presentation/cubit/main_navigation_state.dart',
      '''// GENERATED BY MAGICKIT CLI

class MainNavigationStateCubit {
  final int currentIndex;
  const MainNavigationStateCubit({this.currentIndex = 0});

  MainNavigationStateCubit copyWith({int? currentIndex}) {
    return MainNavigationStateCubit(
      currentIndex: currentIndex ?? this.currentIndex,
    );
  }
}
''',
    );
  }

  void _writeMainNavigationCubit() {
    _writeFile(
      'lib/features/main/main_navigation/presentation/cubit/main_navigation_cubit.dart',
      '''// GENERATED BY MAGICKIT CLI

import '../../../../../core/base/magic_cubit.dart';
import 'main_navigation_state.dart';

class MainNavigationCubit extends MagicCubit<MainNavigationStateCubit> {
  MainNavigationCubit() : super(const MainNavigationStateCubit());

  void setTab(int index) {
    emit(state.copyWith(currentIndex: index));
  }
}
''',
    );
  }

  void _writeMainNavigationPage() {
    _writeFile(
      'lib/features/main/main_navigation/presentation/pages/main_navigation_page.dart',
      r'''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:magickit/magickit.dart';
import '../../../../../core/base/magic_state_page.dart';
import '../../../../../core/dependency_injection/injector.dart';
import '../../../routes/main_route_names.dart';
import '../cubit/main_navigation_cubit.dart';
import '../cubit/main_navigation_state.dart';

class MainNavigationPage extends StatefulWidget {
  final Widget child;
  const MainNavigationPage({super.key, required this.child});

  @override
  State<MainNavigationPage> createState() => _MainNavigationPageState();
}

class _MainNavigationPageState extends State<MainNavigationPage>
    with MagicStatePage<MainNavigationPage, MainNavigationCubit,
        MainNavigationStateCubit> {
  @override
  MainNavigationCubit createCubit() => getIt();

  @override
  Widget buildPage(BuildContext context, MainNavigationStateCubit state) {
    return Scaffold(
      body: widget.child,
      bottomNavigationBar: MagicNavBar(
        currentIndex: state.currentIndex,
        onTap: (index) {
          cubit.setTab(index);
          switch (index) {
            case 0:
              context.go(MainRouteName.homePath);
            case 1:
              context.go(MainRouteName.profilePath);
          }
        },
        items: const [
          MagicNavBarItem(
            icon: Icons.home_outlined,
            activeIcon: Icons.home,
            label: 'Home',
          ),
          MagicNavBarItem(
            icon: Icons.person_outlined,
            activeIcon: Icons.person,
            label: 'Profile',
          ),
        ],
      ),
    );
  }
}
''',
    );
  }

  // ── Home ──────────────────────────────────────────────────────────────────

  void _writeHomeState() {
    _writeFile(
      'lib/features/main/home/presentation/cubit/home_state.dart',
      '''// GENERATED BY MAGICKIT CLI

class HomeStateCubit {
  const HomeStateCubit();
}
''',
    );
  }

  void _writeHomeCubit() {
    _writeFile(
      'lib/features/main/home/presentation/cubit/home_cubit.dart',
      '''// GENERATED BY MAGICKIT CLI

import '../../../../../core/base/magic_cubit.dart';
import 'home_state.dart';

class HomeCubit extends MagicCubit<HomeStateCubit> {
  HomeCubit() : super(const HomeStateCubit());
}
''',
    );
  }

  void _writeHomePage() {
    _writeFile(
      'lib/features/main/home/presentation/pages/home_page.dart',
      r'''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:magickit/magickit.dart';
import '../../../../../core/base/magic_state_page.dart';
import '../../../../../core/dependency_injection/injector.dart';
import '../cubit/home_cubit.dart';
import '../cubit/home_state.dart';

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage>
    with MagicStatePage<HomePage, HomeCubit, HomeStateCubit> {
  @override
  HomeCubit createCubit() => getIt();

  @override
  Widget buildPage(BuildContext context, HomeStateCubit state) {
    final theme = MagicTheme.of(context);
    return Scaffold(
      appBar: MagicAppBar(
        title: 'Home',
        actions: [
          MagicAvatar(
            imageUrl: null,
            fallbackInitial: 'JD',
            size: MagicAvatarSize.sm,
          ),
        ],
      ),
      body: Padding(
        padding: EdgeInsets.all(theme.spacing.md),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            MagicText('Welcome back!', style: theme.typography.heading3),
            SizedBox(height: theme.spacing.xs),
            MagicText(
              "Here's what's happening today",
              style: theme.typography.bodyMedium,
              color: theme.colors.onBackgroundSecondary,
            ),
            SizedBox(height: theme.spacing.lg),
            MagicCard(
              padding: EdgeInsets.all(theme.spacing.md),
              child: Row(
                children: [
                  MagicIcon(
                    icon: Icons.analytics_outlined,
                    size: 40,
                    color: theme.colors.primary,
                  ),
                  SizedBox(width: theme.spacing.md),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        MagicText(
                          'Quick Stats',
                          style: theme.typography.bodyLarge,
                        ),
                        MagicText(
                          'Everything looks great',
                          style: theme.typography.caption,
                          color: theme.colors.onBackgroundSecondary,
                        ),
                      ],
                    ),
                  ),
                  MagicBadge(label: 'New', color: theme.colors.primary),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
''',
    );
  }

  // ── Profile ───────────────────────────────────────────────────────────────

  void _writeProfileState() {
    _writeFile(
      'lib/features/main/profile/presentation/cubit/profile_state.dart',
      '''// GENERATED BY MAGICKIT CLI

class ProfileStateCubit {
  const ProfileStateCubit();
}
''',
    );
  }

  void _writeProfileCubit() {
    _writeFile(
      'lib/features/main/profile/presentation/cubit/profile_cubit.dart',
      '''// GENERATED BY MAGICKIT CLI

import '../../../../../core/base/magic_cubit.dart';
import 'profile_state.dart';

class ProfileCubit extends MagicCubit<ProfileStateCubit> {
  ProfileCubit() : super(const ProfileStateCubit());
}
''',
    );
  }

  void _writeProfilePage() {
    _writeFile(
      'lib/features/main/profile/presentation/pages/profile_page.dart',
      r'''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:magickit/magickit.dart';
import '../../../../../core/base/magic_state_page.dart';
import '../../../../../core/dependency_injection/injector.dart';
import '../../../../auth/routes/auth_route_names.dart';
import '../cubit/profile_cubit.dart';
import '../cubit/profile_state.dart';

class ProfilePage extends StatefulWidget {
  const ProfilePage({super.key});

  @override
  State<ProfilePage> createState() => _ProfilePageState();
}

class _ProfilePageState extends State<ProfilePage>
    with MagicStatePage<ProfilePage, ProfileCubit, ProfileStateCubit> {
  @override
  ProfileCubit createCubit() => getIt();

  @override
  Widget buildPage(BuildContext context, ProfileStateCubit state) {
    final theme = MagicTheme.of(context);
    return Scaffold(
      appBar: MagicAppBar(title: 'Profile'),
      body: Padding(
        padding: EdgeInsets.all(theme.spacing.md),
        child: Column(
          children: [
            SizedBox(height: theme.spacing.lg),
            MagicAvatar(
              imageUrl: null,
              fallbackInitial: 'JD',
              size: MagicAvatarSize.lg,
            ),
            SizedBox(height: theme.spacing.md),
            MagicText('John Doe', style: theme.typography.heading3),
            SizedBox(height: theme.spacing.xs),
            MagicText(
              'test@mail.com',
              style: theme.typography.bodyMedium,
              color: theme.colors.onBackgroundSecondary,
            ),
            SizedBox(height: theme.spacing.xl),
            MagicDivider(),
            SizedBox(height: theme.spacing.sm),
            MagicListTile(
              leading: MagicIcon(
                icon: Icons.settings_outlined,
                color: theme.colors.onBackground,
              ),
              title: 'Settings',
              trailing: MagicIcon(
                icon: Icons.chevron_right,
                color: theme.colors.onBackgroundSecondary,
              ),
              onTap: () {},
            ),
            MagicListTile(
              leading: MagicIcon(
                icon: Icons.help_outline,
                color: theme.colors.onBackground,
              ),
              title: 'Help & Support',
              trailing: MagicIcon(
                icon: Icons.chevron_right,
                color: theme.colors.onBackgroundSecondary,
              ),
              onTap: () {},
            ),
            MagicListTile(
              leading: MagicIcon(
                icon: Icons.info_outline,
                color: theme.colors.onBackground,
              ),
              title: 'About',
              trailing: MagicIcon(
                icon: Icons.chevron_right,
                color: theme.colors.onBackgroundSecondary,
              ),
              onTap: () {},
            ),
            SizedBox(height: theme.spacing.md),
            MagicDivider(),
            SizedBox(height: theme.spacing.md),
            MagicButton(
              label: 'Logout',
              variant: MagicButtonVariant.outlined,
              icon: Icons.logout,
              onPressed: () {
                MagicDialog.show(
                  context: context,
                  title: 'Logout',
                  content: 'Are you sure you want to logout?',
                  actions: [
                    MagicButton(
                      label: 'Cancel',
                      variant: MagicButtonVariant.ghost,
                      onPressed: () => Navigator.pop(context),
                    ),
                    MagicButton(
                      label: 'Logout',
                      variant: MagicButtonVariant.primary,
                      onPressed: () {
                        Navigator.pop(context);
                        context.go(AuthRouteName.loginPath);
                      },
                    ),
                  ],
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}
''',
    );
  }

  // ── main.dart ─────────────────────────────────────────────────────────────

  void _writeMainDart() {
    _writeFile(
      'lib/main.dart',
      '''// GENERATED BY MAGICKIT CLI

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:magickit/magickit.dart';
import 'core/dependency_injection/injector.dart';
import 'core/routes/route_config.dart';
import 'core/assets/l10n/app_localizations.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  configureDependencies();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'MagicKit App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        extensions: [
          MagicTheme(
            colors: MagicColors.light(),
            typography: MagicTypography(),
            spacing: MagicSpacing(),
            radius: MagicRadius(),
            shadows: MagicShadows(),
          ),
        ],
      ),
      routerConfig: routeConfig,
      locale: const Locale('id'),
      supportedLocales: AppLocalizations.supportedLocales,
      localizationsDelegates: [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
    );
  }
}
''',
    );

    logger.info('  main.dart updated');
  }
}
