import 'dart:io';

/// Reads pubspec.yaml, extracts version, and writes lib/src/version.g.dart.
///
/// Run from the package root (packages/magickit_cli/):
///   dart tool/generate_version.dart
void main() {
  final scriptDir = File(Platform.script.toFilePath()).parent.path;
  // When run via `dart tool/generate_version.dart`, script is in tool/.
  final packageDir = Directory(scriptDir).parent.path;

  final pubspecFile = File('$packageDir/pubspec.yaml');
  if (!pubspecFile.existsSync()) {
    stderr.writeln('Error: pubspec.yaml not found at ${pubspecFile.path}');
    exit(1);
  }

  final content = pubspecFile.readAsStringSync();
  final version = _extractVersion(content);

  if (version == null) {
    stderr.writeln('Error: Could not extract version from pubspec.yaml');
    exit(1);
  }

  final outputFile = File('$packageDir/lib/src/version.g.dart');
  outputFile.writeAsStringSync('''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_version.dart

/// The current package version, compiled in at build time.
const String packageVersion = '$version';
''');

  stdout.writeln('Generated version.g.dart with version: $version');
}

String? _extractVersion(String content) {
  for (final line in content.split('\n')) {
    final trimmed = line.trim();
    if (trimmed.startsWith('version:')) {
      return trimmed.substring('version:'.length).trim();
    }
  }
  return null;
}
