name: magickit
description: MagicKit UI Kit — Flutter widget library dengan atomic design pattern.
version: 1.1.0
homepage: https://github.com/worklabsofficial/magickit-flutter
repository: https://github.com/worklabsofficial/magickit-flutter
issue_tracker: https://github.com/worklabsofficial/magickit-flutter/issues
license: Apache-2.0

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.22.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
