import 'dart:io';

import 'string_utils.dart';

class DiUtils {
  static String? readAppName() {
    final pubspec = File('pubspec.yaml');
    if (!pubspec.existsSync()) return null;
    final content = pubspec.readAsStringSync();
    final nameMatch =
        RegExp(r'^name:\s*([A-Za-z0-9_]+)\s*$', multiLine: true)
            .firstMatch(content);
    return nameMatch?.group(1);
  }

  static bool updateFeatureInjector({
    required String feature,
    required String page,
  }) {
    final featureSnake = toSnakeCase(feature);
    final featureCamel = toCamelCase(feature);
    final pageSnake = toSnakeCase(page);
    final pagePascal = toPascalCase(page);
    final injectorPath = 'lib/features/$feature/${featureSnake}_injector.dart';

    final file = File(injectorPath);
    if (!file.existsSync()) {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(_featureInjectorTemplate(featureCamel));
    }

    var content = file.readAsStringSync();
    var modified = false;

    final importLine =
        "import '$pageSnake/presentation/cubit/${pageSnake}_cubit.dart';";
    const markerImport = '// MAGICKIT:IMPORT';
    if (!content.contains(importLine)) {
      if (content.contains(markerImport)) {
        content = content.replaceFirst(
          markerImport,
          '$importLine\n$markerImport',
        );
        modified = true;
      } else {
        final lastImportEnd = content.lastIndexOf("';") + 2;
        if (lastImportEnd > 1) {
          content =
              '${content.substring(0, lastImportEnd)}\n$importLine${content.substring(lastImportEnd)}';
          modified = true;
        }
      }
    }

    final registerLine = '  getIt.registerFactory(() => ${pagePascal}Cubit());';
    const markerInjector = '// MAGICKIT:INJECTOR';
    if (!content.contains(registerLine)) {
      if (content.contains(markerInjector)) {
        content = content.replaceFirst(
          markerInjector,
          '$registerLine\n  $markerInjector',
        );
        modified = true;
      } else {
        final fn = 'void ${featureCamel}Injector()';
        final fnIdx = content.indexOf(fn);
        if (fnIdx != -1) {
          final closeIdx = content.indexOf('}', fnIdx);
          if (closeIdx != -1) {
            content =
                '${content.substring(0, closeIdx)}$registerLine\n${content.substring(closeIdx)}';
            modified = true;
          }
        }
      }
    }

    if (modified) file.writeAsStringSync(content);
    return modified;
  }

  static bool updateGlobalInjector({
    required String appName,
    required String feature,
  }) {
    final injectorFile = File('lib/core/dependency_injection/injector.dart');
    if (!injectorFile.existsSync()) return false;

    var content = injectorFile.readAsStringSync();
    final featureSnake = toSnakeCase(feature);
    final importLine =
        "import 'package:$appName/features/$feature/${featureSnake}_injector.dart';";
    const markerImport = '// MAGICKIT:IMPORT';
    const markerInjector = '// MAGICKIT:INJECTOR';
    final callLine = '${toCamelCase(feature)}Injector();';

    var modified = false;

    if (!content.contains(importLine) && content.contains(markerImport)) {
      content = content.replaceFirst(
        markerImport,
        '$importLine\n$markerImport',
      );
      modified = true;
    }

    if (!content.contains(callLine) && content.contains(markerInjector)) {
      content = content.replaceFirst(
        markerInjector,
        '  $callLine\n  $markerInjector',
      );
      modified = true;
    }

    if (modified) injectorFile.writeAsStringSync(content);
    return modified;
  }

  static String _featureInjectorTemplate(String featureCamel) => '''
// GENERATED BY MAGICKIT CLI

import 'package:get_it/get_it.dart';
// MAGICKIT:IMPORT

final getIt = GetIt.instance;

void ${featureCamel}Injector() {
  // MAGICKIT:INJECTOR
}
''';
}
