import 'dart:io';

import 'package:path/path.dart' as p;

enum GeneratedWriteResult {
  created,
  updated,
  unchanged,
  skippedUserOwned,
}

bool isGeneratedSource(String content) {
  return content.startsWith('// GENERATED CODE') ||
      content.startsWith('// GENERATED BY MAGICKIT CLI');
}

String normalizeSourcePath(String path) {
  return p.normalize(path).replaceAll('\\', '/');
}

/// Write [content] when the file is new, unchanged, generated, or [force] is set.
///
/// Files that exist and do not carry a generated-source header are left in
/// place unless [force] is true.
GeneratedWriteResult writeGeneratedSource({
  required String path,
  required String content,
  required bool force,
}) {
  final file = File(path);
  if (!file.existsSync()) {
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
    return GeneratedWriteResult.created;
  }

  final existing = file.readAsStringSync();
  if (existing == content) return GeneratedWriteResult.unchanged;

  if (!force && !isGeneratedSource(existing)) {
    return GeneratedWriteResult.skippedUserOwned;
  }

  file.writeAsStringSync(content);
  return GeneratedWriteResult.updated;
}

class StaleGeneratedCleanup {
  final List<String> deleted;
  final List<String> keptUserOwned;

  const StaleGeneratedCleanup({
    required this.deleted,
    required this.keptUserOwned,
  });
}

/// Delete generated Dart files under [directories] that are not in [keepPaths].
///
/// User-owned files (no generated header) are reported and kept.
StaleGeneratedCleanup deleteStaleGeneratedSources({
  required List<String> keepPaths,
  required List<String> directories,
}) {
  final keep = keepPaths.map(normalizeSourcePath).toSet();
  final deleted = <String>[];
  final keptUserOwned = <String>[];

  for (final dirPath in directories) {
    final dir = Directory(dirPath);
    if (!dir.existsSync()) continue;

    final files = dir
        .listSync(recursive: false)
        .whereType<File>()
        .where((file) => file.path.endsWith('.dart'))
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));

    for (final file in files) {
      final path = normalizeSourcePath(file.path);
      if (keep.contains(path)) continue;

      final content = file.readAsStringSync();
      if (!isGeneratedSource(content)) {
        keptUserOwned.add(path);
        continue;
      }

      file.deleteSync();
      deleted.add(path);
    }
  }

  return StaleGeneratedCleanup(
    deleted: deleted,
    keptUserOwned: keptUserOwned,
  );
}
